title: Guilherme Carreiro
author: Guilherme Carreiro
email: karreiro@gmail.com
description: >
  Hi, I’m Guilherme Carreiro, aka karreiro :-)
baseurl: ""
url: "http://karreiro.com"
twitter_username: karreiro_
github_username: karreiro
markdown: kramdown
permalink: pretty
highlighted_posts: false
exclude:
  - Gemfile*
  - Rakefile
plugins:
  - jekyll-feed

talks:
  - title: "JavaScript<br />The Right Way"
    conference: "FLISOL Campinas"
    year: 2013
    color: "#FBAA18"
    file_name: "2013-javascript-the-right-way.pdf"

  - title: "High-quality JavaScript"
    conference: "DevCamp / TDC São Paulo"
    year: 2014
    color: "#387EA4"
    file_name: "2014-qualidade-js.pdf"

  - title: "Metaprogramming in practice<br />with Ruby"
    conference: "TDC Florianópolis"
    year: 2015
    color: "#626A8A"
    file_name: "2015-tdc-metaprogramacao.pdf"

  - title: "DSLs with Ruby"
    conference: "TDC São Paulo"
    year: 2015
    color: "#CA6063"
    file_name: "2015-dsls-ruby.pdf"

  - title: "Action Cable<br />in Action"
    conference: "TDC São Paulo / Rupy"
    year: 2016
    color: "#5E327C"
    file_name: "2016-actioncable.pdf"

  - title: "5 pillars of a successful Java web application"
    conference: "Red Hat Forum / JUG Campinas"
    year: 2017
    color: "#A73636"
    file_name: "2017-5pilares.pdf"

  - title: "Design Patterns 101"
    conference: "Campus Party"
    year: 2018
    color: "#88304E"
    file_name: "2018-design-patterns.pdf"

  - title: "Keeping your monolith alive in a high-availability environment"
    conference: "TDC Porto Alegre"
    year: 2019
    color: "#0f5855"
    file_name: "2019-mantendo-seu-monolito-vivo.pdf"

  - title: "DMN for Developers"
    conference: "Kie community live"
    year: 2020
    color: "#af1d60"
    file_name: "2020-dmn-for-developers.pdf"

  - title: "How to play<br />with DMN"
    conference: "Kie community live"
    year: 2021
    color: "#231c33"
    file_name: "2021-how-to-play-with-dmn.pdf"

  - title: "Building native Ruby<br />extensions in Rust"
    conference: "EuRuKo / Baltic Ruby"
    year: 2024
    color: "#121c33"
    file_name: "2024-euruko-building-native-ruby-extensions-in-rust.pdf"
